<?php
echo "<!DOCTYPE html>\n"; 
echo "<html lang=\"en\">\n"; 
echo "  <head>\n"; 
echo "    <meta charset=\"utf-8\">\n"; 
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"; 
echo "    <meta name=\"description\" content=\"SHIELD - Free Bootstrap 3 Theme\">\n"; 
echo "    <meta name=\"author\" content=\"Carlos Alvarez - Alvarez.is - blacktie.co\">\n"; 
echo "    <link rel=\"shortcut icon\" href=\"assets/ico/favicon.png\">\n"; 
echo "\n"; 
echo "    <title> Bed and Breakfast at Willow Lake</title>\n"; 
echo "\n"; 
echo "    <!-- Bootstrap core CSS -->\n"; 
echo "    <link href=\"assets/css/bootstrap.css\" rel=\"stylesheet\">\n"; 
echo "\n"; 
echo "    <!-- Custom styles for this template -->\n"; 
echo "    <link href=\"assets/css/main.css\" rel=\"stylesheet\">\n"; 
echo "    <link rel=\"stylesheet\" href=\"assets/css/icomoon.css\">\n"; 
echo "    <link href=\"assets/css/animate-custom.css\" rel=\"stylesheet\">\n"; 
echo "\n"; 
echo "\n"; 
echo "    \n"; 
echo "    <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic' rel='stylesheet' type='text/css'>\n"; 
echo "    <link href='http://fonts.googleapis.com/css?family=Raleway:400,300,700' rel='stylesheet' type='text/css'>\n"; 
echo "    \n"; 
echo "    <script src=\"assets/js/jquery.min.js\"></script>\n"; 
echo "	<script type=\"text/javascript\" src=\"assets/js/modernizr.custom.js\"></script>\n"; 
echo "    \n"; 
echo "    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->\n"; 
echo "    <!--[if lt IE 9]>\n"; 
echo "      <script src=\"assets/js/html5shiv.js\"></script>\n"; 
echo "      <script src=\"assets/js/respond.min.js\"></script>\n"; 
echo "    <![endif]-->\n"; 
echo "  \n"; 
echo "\n"; 
echo "<!-- Start WOWSlider.com HEAD section -->\n"; 
echo "	<link rel=\"stylesheet\" type=\"text/css\" href=\"engine1//style.css\" media=\"screen\" />\n"; 
echo "	<script type=\"text/javascript\" src=\"engine1//jquery.js\"></script>\n"; 
echo "<!-- End WOWSlider.com HEAD section -->\n"; 
echo "\n"; 
echo "\n"; 
echo "\n"; 
echo "<!-- Start WOWSlider.com HEAD section -->\n"; 
echo "	<link rel=\"stylesheet\" type=\"text/css\" href=\"engine2//style.css\" media=\"screen\" />\n"; 
echo "	<script type=\"text/javascript\" src=\"engine2//jquery.js\"></script>\n"; 
echo "<!-- End WOWSlider.com HEAD section -->\n"; 
echo "\n"; 
echo "\n"; 
echo "\n"; 
echo "<!-- Start WOWSlider.com HEAD section -->\n"; 
echo "	<link rel=\"stylesheet\" type=\"text/css\" href=\"engine3//style.css\" media=\"screen\" />\n"; 
echo "	<script type=\"text/javascript\" src=\"engine3//jquery.js\"></script>\n"; 
echo "<!-- End WOWSlider.com HEAD section -->\n"; 
echo "\n"; 
echo "\n"; 
echo "\n"; 
echo "<!-- Start WOWSlider.com HEAD section -->\n"; 
echo "	<link rel=\"stylesheet\" type=\"text/css\" href=\"engine4//style.css\" media=\"screen\" />\n"; 
echo "	<script type=\"text/javascript\" src=\"engine4//jquery.js\"></script>\n"; 
echo "<!-- End WOWSlider.com HEAD section -->\n"; 
echo "\n"; 
echo "\n"; 
echo "\n"; 
echo "<!-- Start WOWSlider.com HEAD section -->\n"; 
echo "	<link rel=\"stylesheet\" type=\"text/css\" href=\"engine5//style.css\" media=\"screen\" />\n"; 
echo "	<script type=\"text/javascript\" src=\"engine5//jquery.js\"></script>\n"; 
echo "<!-- End WOWSlider.com HEAD section -->\n"; 
echo "\n"; 
echo "</head>\n"; 
echo "\n"; 
echo "  <body data-spy=\"scroll\" data-offset=\"0\" data-target=\"#navbar-main\">\n"; 
echo "  \n"; 
echo "  \n"; 
echo "  	 <div id=\"navbar-main\"> \n"; 
echo "      <!-- Fixed navbar -->\n"; 
echo "     <div class=\"navbar navbar-inverse navbar-fixed-top\"> \n"; 
echo "      <div class=\"container\">\n"; 
echo "        <div class=\"navbar-header\">\n"; 
echo "          \n"; 
echo "        </div>\n"; 
echo "        <div class=\"navbar-collapse collapse\">\n"; 
echo "          <ul class=\"nav navbar-nav\">\n"; 
echo "            <li><a href=\"#home\" class=\"smoothScroll\">Home</a></li>\n"; 
echo "			<li> <a href=\"#about\" class=\"smoothScroll\"> About</a></li>\n"; 
echo "			<li> <a href=\"#services\" class=\"smoothScroll\"> Rooming and Accommodations</a></li>\n"; 
echo "			<li> <a href=\"#menu\" class=\"smoothScroll\"> Menu</a></li>\n"; 
echo "			<li> <a href=\"#attract\" class=\"smoothScroll\"> Local Attractions</a></li>\n"; 
echo "			<li> <a href=\"#contact\" class=\"smoothScroll\"> Contact</a></li> \n"; 
echo "        </div><!--/.nav-collapse --> \n"; 
echo "      </div>\n"; 
echo "     </div>\n"; 
echo "    </div>\n"; 
echo "    \n"; 
echo "  \n"; 
echo "		<!-- ==== HEADERWRAP ==== -->\n"; 
echo "	    <div id=\"headerwrap\" id=\"home\" name=\"home\">\n"; 
echo "			<header class=\"clearfix\">\n"; 
echo "	  		 		<h1><br></h1>\n"; 
echo "	  		 		<p>Bed and Breakfast at Willow Lake</p>\n"; 
echo "	  		 		<p>We offer you a luxurious time here.</p>\n"; 
echo "	  		</header>	    \n"; 
echo "	    </div><!-- /headerwrap -->\n"; 
echo "\n"; 
echo "		<!-- ==== GREYWRAP ==== -->\n"; 
echo "		<div id=\"greywrap\">\n"; 
echo "			<div class=\"row\">\n"; 
echo "				<div class=\"col-lg-4 callout\">\n"; 
echo "					<span class=\"icon icon-home\"></span>\n"; 
echo "					<h2>Rooms</h2>\n"; 
echo "					<p>We offer honeymoon and anniversary packages, extended stay packages, and general one- or two-night accommodations for travelers.</p>\n"; 
echo "				</div><!-- col-lg-4 -->\n"; 
echo "					\n"; 
echo "				<div class=\"col-lg-4 callout\">\n"; 
echo "					<span class=\"icon icon-pie\"></span>\n"; 
echo "					<h2>Food</h2>\n"; 
echo "					<p>The French- inspired breakfast menu includes fruit and cheese crepes, various croissants, as well as gluten-free options. </p>\n"; 
echo "				</div><!-- col-lg-4 -->	\n"; 
echo "				\n"; 
echo "				<div class=\"col-lg-4 callout\">\n"; 
echo "					<span class=\"icon icon-music\"></span>\n"; 
echo "					<h2>Fun</h2>\n"; 
echo "					<p>There are many attractions near us that will keep you active and entertaned with your loved ones. </p>\n"; 
echo "				</div><!-- col-lg-4 -->	\n"; 
echo "			</div><!-- row -->\n"; 
echo "		</div><!-- greywrap -->\n"; 
echo "		\n"; 
echo "		<!-- ==== ABOUT ==== -->\n"; 
echo "		<div class=\"container\" id=\"about\" name=\"about\">\n"; 
echo "			<div class=\"row white\">\n"; 
echo "			<br>\n"; 
echo "				<h1 class=\"centered\">A LITTLE ABOUT US</h1>\n"; 
echo "				<hr>\n"; 
echo "				\n"; 
echo "				<div class=\"col-lg-12\">\n"; 
echo "					<p>The Willow Lake Bed & Breakfast is a French inspired get away to Elmwood, NJ. Travelers can enjoy one- or two-night accommodations. For Couple we provide honeymoon, anniversary and extended stay accommodations. We provide breakfast, lunch, tea party service, and dinner for guests and special occasions. This 1800s refurbished home includes authentically furnished living and dining rooms, and an outdoor patio with formal gardens perfect for entertaining. Visits are always welcome and we are more than willing to make your stay perfect. </p>\n"; 
echo "					<style>\n"; 
echo "						p{\n"; 
echo "							text-align: center;\n"; 
echo "						}\n"; 
echo "					</style>\n"; 
echo "				</div><!-- col-lg-6 -->\n"; 
echo "				\n"; 
echo "				\n"; 
echo "			</div><!-- row -->\n"; 
echo "		</div><!-- container -->\n"; 
echo "	\n"; 
echo "		<!-- ==== SERVICES ==== -->\n"; 
echo "		<div class=\"container\" id=\"services\" name=\"services\">\n"; 
echo "			<br>\n"; 
echo "			<div class=\"row\">\n"; 
echo "				<h2 class=\"centered\">ROOMING AND ACCOMMODATIONS</h2>\n"; 
echo "				<hr>\n"; 
echo "				<br>\n"; 
echo "			</div><!-- row -->\n"; 
echo "			\n"; 
echo "<!-- Start WOWSlider.com BODY section id=wowslider-container3 -->\n"; 
echo "\n"; 
echo "    <div id=\"wowslider-container3\">\n"; 
echo "        <div class=\"ws_images\">\n"; 
echo "            <ul>\n"; 
echo "                <li><img alt=\"\" id=\"wows3_0\" name=\"wows3_0\" src=\n"; 
echo "                \"data3/images/11_thumb.jpg\" title=\"\"></li>\n"; 
echo "\n"; 
echo "                <li><img alt=\"\" id=\"wows3_1\" name=\"wows3_1\" src=\n"; 
echo "                \"data3/images/6729279627_cddfe4e61d_b.jpg\" title=\"\"></li>\n"; 
echo "\n"; 
echo "                <li><img alt=\"\" id=\"wows3_2\" name=\"wows3_2\" src=\n"; 
echo "                \"data3/images/bnan934_1128bn_m_20131125175546.jpg\" title=\n"; 
echo "                \"\"></li>\n"; 
echo "\n"; 
echo "                <li><img alt=\"\" id=\"wows3_3\" name=\"wows3_3\" src=\n"; 
echo "                \"data3/images/wmdsc_6074_1454.jpg\" title=\"\"></li>\n"; 
echo "            </ul>\n"; 
echo "        </div>\n"; 
echo "\n"; 
echo "        <div class=\"ws_bullets\">\n"; 
echo "            <div>\n"; 
echo "                <a href=\"#\" title=\"\"><img alt=\"\" src=\n"; 
echo "                \"data3/tooltips/11_thumb.jpg\">1</a> <a href=\"#\" title=\n"; 
echo "                \"\"><img alt=\"\" src=\n"; 
echo "                \"data3/tooltips/6729279627_cddfe4e61d_b.jpg\">2</a> <a href=\"#\"\n"; 
echo "                title=\"\"><img alt=\"\" src=\n"; 
echo "                \"data3/tooltips/bnan934_1128bn_m_20131125175546.jpg\">3</a>\n"; 
echo "                <a href=\"#\" title=\"\"><img alt=\"\" src=\n"; 
echo "                \"data3/tooltips/wmdsc_6074_1454.jpg\">4</a>\n"; 
echo "            </div>\n"; 
echo "        </div><span class=\"wsl\"><a href=\"http://wowslider.com\">Js Gallery</a>\n"; 
echo "        by WOWSlider.com v5.0m</span> <a class=\"ws_frame\" href=\"#\"></a>\n"; 
echo "\n"; 
echo "        <div class=\"ws_shadow\"></div>\n"; 
echo "    </div><script src=\"engine3//wowslider.js\" type=\"text/javascript\"></script><script src=\"engine3//script.js\" type=\"text/javascript\"></script><!-- End WOWSlider.com BODY section -->\n"; 
echo "\n"; 
echo "<div class=\"row\">\n"; 
echo "			<br>\n"; 
echo "			<div class=\"row\">\n"; 
echo "				<table>\n"; 
echo "					<tr>\n"; 
echo "						<td><strong>ROOM ACCOMMODATIONS*</strong></td>\n"; 
echo "						<td><strong>PRICE</strong></td>\n"; 
echo "					</tr>\n"; 
echo "					<tr>\n"; 
echo "						<td>Standard Suite: <br>\n"; 
echo "							<ul>\n"; 
echo "							<li>Typically for one-two night accommodations</li>\n"; 
echo "							<li>Includes the Tempurpedic Queen Sized Bed</li>\n"; 
echo "							<li>Bathroom includes Multi Precision shower and single fixture sink</li>\n"; 
echo "							</ul>\n"; 
echo "						</td>\n"; 
echo "						<td>$225 for 1 night<br>\n"; 
echo "							$375 for 2 nights<br>\n"; 
echo "							$1,050 for a week\n"; 
echo "						</td>\n"; 
echo "					</tr>\n"; 
echo "					<tr>\n"; 
echo "						<td>Honeymoon Suite: <br>\n"; 
echo "							<ul>\n"; 
echo "								<li>Includes the Tempurpedic King Sized bed and minibar**</li>\n"; 
echo "								<li>Bathroom includes dual fixture sink, imported Victorian bathtub and <br>\n"; 
echo "									Multi Precision shower</li>\n"; 
echo "								<li>Floral arrangements of your choosing available</li>\n"; 
echo "							</ul>\n"; 
echo "						</td>\n"; 
echo "						<td>\n"; 
echo "							$425 for 2 night stay <br>\n"; 
echo "							$750 for 4 night stay <br>\n"; 
echo "							$2,425 for a week\n"; 
echo "						</td>\n"; 
echo "					</tr>\n"; 
echo "					<tr>\n"; 
echo "						<td>\n"; 
echo "							Anniversary Suite: <br>\n"; 
echo "							<ul>\n"; 
echo "								<li>Includes the Tempurpedic King Sized bed, terrace, seating room and minibar**</li>\n"; 
echo "								<li>Bathroom includes dual fixture sink, Jacuzzi bath tub and Multi Precision Shower</li>\n"; 
echo "								<li>Welcome gifts and first-night dinners are on us.</li>\n"; 
echo "								<li>Floral arrangements of your choosing available</li>\n"; 
echo "								<li>Tickets to the local movie theater</li>\n"; 
echo "							</ul>\n"; 
echo "						</td>\n"; 
echo "						<td>\n"; 
echo "							$545 for 2 night stay <br>\n"; 
echo "							$965 for 4 night stay <br>\n"; 
echo "							$3,375 for a week\n"; 
echo "						</td>\n"; 
echo "					</tr>\n"; 
echo "					<tr>\n"; 
echo "						<td>\n"; 
echo "							*Complementary coffee is provided <br>\n"; 
echo "							**Minibar contains small fridge, sink, champagne glasses, and a bottle of Tuscan Champagne <br>\n"; 
echo "							All rooms contain a safe, walk in closet and HD Television\n"; 
echo "							</ul>\n"; 
echo "						</td>\n"; 
echo "					</tr>\n"; 
echo "				</table>	\n"; 
echo "		</div><!-- container -->\n"; 
echo "  		\n"; 
echo "		<!-- ==== Menu ==== -->\n"; 
echo "		<div class=\"container\" id=\"menu\" name=\"blog\">\n"; 
echo "		<br>\n"; 
echo "			<div class=\"row\">\n"; 
echo "				<br>\n"; 
echo "				<h1 class=\"centered\">MENU</h1>\n"; 
echo "				<hr>\n"; 
echo "				<br>\n"; 
echo "				<br>\n"; 
echo "			</div><!-- /row -->\n"; 
echo "			\n"; 
echo "			<div class=\"row\">\n"; 
echo "				<div class=\"col-lg-6 blog-bg\">\n"; 
echo "					<div class=\"col-lg-4 centered\">\n"; 
echo "						<img src=\"assets/img/Flaticon_bell.png\">\n"; 
echo "					<br>\n"; 
echo "					</div>\n"; 
echo "					<div class=\"col-lg-8 blog-content\">\n"; 
echo "						<h2>Daily Meals</h2>\n"; 
echo "						<p>Our menu includes authentic French cuisine. The light, savory and sweet flavors of the French countryside are infused into our wide array of desserts, pastries, and breads. Recently, we have included a French Bistro styled cuisine for our dinner and lunch menus.  Gluten-free options are also provided.  </p>\n"; 
echo "						<p><a href=\"https://www.dropbox.com/s/i14bgnoxh4mdddy/General%20Menu.pdf\" target=\"_blank\"> Download Menu</a></p>\n"; 
echo "						<br>\n"; 
echo "						<hr>\n"; 
echo "					</div>\n"; 
echo "				</div><!-- /col -->\n"; 
echo "				\n"; 
echo "				<div class=\"col-lg-6 blog-bg\">\n"; 
echo "					<div class=\"col-lg-4 centered\">\n"; 
echo "						<img src=\"assets/img/Flaticon_teacup.png\">\n"; 
echo "					<br>\n"; 
echo "					</div>\n"; 
echo "					<div class=\"col-lg-8 blog-content\">\n"; 
echo "						<h2>Tea Party Service</h2>\n"; 
echo "						<p>Our afternoon Tea Party service includes high-end custom teas and finger sandwiches with an assortment of finger-food dessert options. This event is hosted for special occasions such as business events, birthdays and wedding/shower parties. </p>\n"; 
echo "						<br>\n"; 
echo "						<p><a href=\"https://www.dropbox.com/s/qb1ub67t2e2ao25/Tea%20Party%20Menu.pdf\" target=\"_blank\"> Download Menu</a></p>\n"; 
echo "						<br>\n"; 
echo "						<hr>\n"; 
echo "						<style>\n"; 
echo "							h2{\n"; 
echo "								text-align: center;\n"; 
echo "							}\n"; 
echo "						</style>\n"; 
echo "					</div>\n"; 
echo "				</div><!-- /col -->\n"; 
echo "			</div><!-- /row -->\n"; 
echo "	\n"; 
echo "\n"; 
echo "<!-- Start WOWSlider.com BODY section id=wowslider-container5 -->\n"; 
echo "	<div id=\"wowslider-container5\">\n"; 
echo "	<div class=\"ws_images\"><ul>\n"; 
echo "<li><img src=\"data5/images/04_bosieteaparlor.jpg\" alt=\"\" title=\"\" id=\"wows5_0\"/></li>\n"; 
echo "<li><img src=\"data5/images/1801097785_b9890d58f2.jpg\" alt=\"\" title=\"\" id=\"wows5_1\"/></li>\n"; 
echo "<li><img src=\"data5/images/3171576410_fedd5b5e14.jpg\" alt=\"\" title=\"\" id=\"wows5_2\"/></li>\n"; 
echo "<li><img src=\"data5/images/5598616822_6e8e6ed843_b.jpg\" alt=\"\" title=\"\" id=\"wows5_3\"/></li>\n"; 
echo "<li><img src=\"data5/images/5819686811_2cf0853572_b.jpg\" alt=\"\" title=\"\" id=\"wows5_4\"/></li>\n"; 
echo "<li><img src=\"data5/images/5819698807_04dd5463da_b.jpg\" alt=\"\" title=\"\" id=\"wows5_5\"/></li>\n"; 
echo "<li><img src=\"data5/images/5819850281_09de9ddcd2_b.jpg\" alt=\"\" title=\"\" id=\"wows5_6\"/></li>\n"; 
echo "<li><img src=\"data5/images/5820277286_03957d0047_b.jpg\" alt=\"\" title=\"\" id=\"wows5_7\"/></li>\n"; 
echo "<li><img src=\"data5/images/5820306510_e51f07ee7c_b.jpg\" alt=\"\" title=\"\" id=\"wows5_8\"/></li>\n"; 
echo "<li><img src=\"data5/images/6287840922_ea5a81faf3_b.jpg\" alt=\"\" title=\"\" id=\"wows5_9\"/></li>\n"; 
echo "<li><img src=\"data5/images/6934291931_fdb6f1f64f.jpg\" alt=\"\" title=\"\" id=\"wows5_10\"/></li>\n"; 
echo "<li><img src=\"data5/images/7983758730_482520f202_b.jpg\" alt=\"\" title=\"\" id=\"wows5_11\"/></li>\n"; 
echo "<li><img src=\"data5/images/9580869785_3b7eba68a7_z.jpg\" alt=\"\" title=\"\" id=\"wows5_12\"/></li>\n"; 
echo "<li><img src=\"data5/images/orig.jpg\" alt=\"\" title=\"\" id=\"wows5_13\"/></li>\n"; 
echo "<li><img src=\"data5/images/savorycrepe.jpg\" alt=\"\" title=\"\" id=\"wows5_14\"/></li>\n"; 
echo "<li><img src=\"data5/images/sweetandsavorycrepes1.jpg\" alt=\"\" title=\"\" id=\"wows5_15\"/></li>\n"; 
echo "<li><img src=\"data5/images/tumblr_m6ejoj435k1r4i14no1_500.jpg\" alt=\"\" title=\"\" id=\"wows5_16\"/></li>\n"; 
echo "<li><img src=\"data5/images/tumblr_mzuls3mwur1rzwv55o1_500.png\" alt=\"\" title=\"\" id=\"wows5_17\"/></li>\n"; 
echo "</ul></div>\n"; 
echo "<div class=\"ws_bullets\"><div>\n"; 
echo "<a href=\"#\" title=\"\"><img src=\"data5/tooltips/04_bosieteaparlor.jpg\" alt=\"\"/>1</a>\n"; 
echo "<a href=\"#\" title=\"\"><img src=\"data5/tooltips/1801097785_b9890d58f2.jpg\" alt=\"\"/>2</a>\n"; 
echo "<a href=\"#\" title=\"\"><img src=\"data5/tooltips/3171576410_fedd5b5e14.jpg\" alt=\"\"/>3</a>\n"; 
echo "<a href=\"#\" title=\"\"><img src=\"data5/tooltips/5598616822_6e8e6ed843_b.jpg\" alt=\"\"/>4</a>\n"; 
echo "<a href=\"#\" title=\"\"><img src=\"data5/tooltips/5819686811_2cf0853572_b.jpg\" alt=\"\"/>5</a>\n"; 
echo "<a href=\"#\" title=\"\"><img src=\"data5/tooltips/5819698807_04dd5463da_b.jpg\" alt=\"\"/>6</a>\n"; 
echo "<a href=\"#\" title=\"\"><img src=\"data5/tooltips/5819850281_09de9ddcd2_b.jpg\" alt=\"\"/>7</a>\n"; 
echo "<a href=\"#\" title=\"\"><img src=\"data5/tooltips/5820277286_03957d0047_b.jpg\" alt=\"\"/>8</a>\n"; 
echo "<a href=\"#\" title=\"\"><img src=\"data5/tooltips/5820306510_e51f07ee7c_b.jpg\" alt=\"\"/>9</a>\n"; 
echo "<a href=\"#\" title=\"\"><img src=\"data5/tooltips/6287840922_ea5a81faf3_b.jpg\" alt=\"\"/>10</a>\n"; 
echo "<a href=\"#\" title=\"\"><img src=\"data5/tooltips/6934291931_fdb6f1f64f.jpg\" alt=\"\"/>11</a>\n"; 
echo "<a href=\"#\" title=\"\"><img src=\"data5/tooltips/7983758730_482520f202_b.jpg\" alt=\"\"/>12</a>\n"; 
echo "<a href=\"#\" title=\"\"><img src=\"data5/tooltips/9580869785_3b7eba68a7_z.jpg\" alt=\"\"/>13</a>\n"; 
echo "<a href=\"#\" title=\"\"><img src=\"data5/tooltips/orig.jpg\" alt=\"\"/>14</a>\n"; 
echo "<a href=\"#\" title=\"\"><img src=\"data5/tooltips/savorycrepe.jpg\" alt=\"\"/>15</a>\n"; 
echo "<a href=\"#\" title=\"\"><img src=\"data5/tooltips/sweetandsavorycrepes1.jpg\" alt=\"\"/>16</a>\n"; 
echo "<a href=\"#\" title=\"\"><img src=\"data5/tooltips/tumblr_m6ejoj435k1r4i14no1_500.jpg\" alt=\"\"/>17</a>\n"; 
echo "<a href=\"#\" title=\"\"><img src=\"data5/tooltips/tumblr_mzuls3mwur1rzwv55o1_500.png\" alt=\"\"/>18</a>\n"; 
echo "</div></div>\n"; 
echo "<span class=\"wsl\"><a href=\"http://wowslider.com\">Js Gallery</a> by WOWSlider.com v5.0m</span>\n"; 
echo "	<a href=\"#\" class=\"ws_frame\"></a>\n"; 
echo "	<div class=\"ws_shadow\"></div>\n"; 
echo "	</div>\n"; 
echo "	<script type=\"text/javascript\" src=\"engine5//wowslider.js\"></script>\n"; 
echo "	<script type=\"text/javascript\" src=\"engine5//script.js\"></script>\n"; 
echo "<!-- End WOWSlider.com BODY section -->\n"; 
echo "\n"; 
echo "		</div><!-- /container -->\n"; 
echo "		\n"; 
echo "\n"; 
echo "		<!--</section><!-- section -->\n"; 
echo "		\n"; 
echo "		<!-- ==== PORTFOLIO ==== -->\n"; 
echo "		<div class=\"container\" id=\"attract\" name=\"portfolio\">\n"; 
echo "		<br>\n"; 
echo "			<div class=\"row\">\n"; 
echo "				<br>\n"; 
echo "				<h1 class=\"centered\">LOCAL ATTRACTIONS</h1>\n"; 
echo "				<hr>\n"; 
echo "				<br>\n"; 
echo "				<br>\n"; 
echo "			</div><!-- /row -->\n"; 
echo "			<div class=\"container\">\n"; 
echo "			<div class=\"row\">	\n"; 
echo "			\n"; 
echo "				<!-- PORTFOLIO IMAGE 1 -->\n"; 
echo "				<div class=\"col-md-4 \">\n"; 
echo "			    	<div class=\"grid mask\">\n"; 
echo "						<figure>\n"; 
echo "							<img class=\"img-responsive\" src=\"assets/img/attractions/oooo.jpg\" alt=\"\">\n"; 
echo "							<figcaption>\n"; 
echo "								<h5>Spa & Nail Salon</h5>\n"; 
echo "								<a data-toggle=\"modal\" href=\"#myModal1\" class=\"btn btn-primary btn-lg\">Take a Look</a>\n"; 
echo "							</figcaption><!-- /figcaption -->\n"; 
echo "						</figure><!-- /figure -->\n"; 
echo "			    	</div><!-- /grid-mask -->\n"; 
echo "				</div><!-- /col -->\n"; 
echo "						      \n"; 
echo "						  <div class=\"modal fade\" id=\"myModal1\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\n"; 
echo "						    <div class=\"modal-dialog\">\n"; 
echo "						      <div class=\"modal-content\">\n"; 
echo "						        <div class=\"modal-header\">\n"; 
echo "						          <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">&times;</button>\n"; 
echo "						          <h4 class=\"modal-title\">Yumi’s Organic Day Spa & Nail Salon</h4>\n"; 
echo "						        </div>\n"; 
echo "						        <div class=\"modal-body\">\n"; 
echo "						          <p><img class=\"img-responsive\" src=\"assets/img/attractions/oooo.jpg\" alt=\"\"></p>\n"; 
echo "						          <p>Sit back and relax at the spa with a loved one or friend and enjoy professional facial and full body massages. Relax in their sauna or mud baths and indulge yourself with a traditional seaweed wrap. Enjoy the bliss of a pedicure and manicure for elegant nails. View their site for prices and accommodations.</p>\n"; 
echo "						          <p><b><a href=\"#\">Visit Site</a></b></p>\n"; 
echo "						        </div>\n"; 
echo "						        <div class=\"modal-footer\">\n"; 
echo "						          <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\n"; 
echo "						        </div>\n"; 
echo "						      </div><!-- /.modal-content -->\n"; 
echo "						    </div><!-- /.modal-dialog -->\n"; 
echo "						  </div><!-- /.modal -->\n"; 
echo "				\n"; 
echo "				\n"; 
echo "				<!-- PORTFOLIO IMAGE 2 -->\n"; 
echo "				<div class=\"col-md-4\">\n"; 
echo "			    	<div class=\"grid mask\">\n"; 
echo "						<figure>\n"; 
echo "							<img class=\"img-responsive\" src=\"assets/img/attractions/boat.jpg\" alt=\"\">\n"; 
echo "							<figcaption>\n"; 
echo "								<h5>Oceanic Sailing</h5>\n"; 
echo "								<a data-toggle=\"modal\" href=\"#myModal2\" class=\"btn btn-primary btn-lg\">Take a Look</a>\n"; 
echo "							</figcaption><!-- /figcaption -->\n"; 
echo "						</figure><!-- /figure -->\n"; 
echo "			    	</div><!-- /grid-mask -->\n"; 
echo "				</div><!-- /col -->\n"; 
echo "\n"; 
echo "							<div class=\"modal fade\" id=\"myModal2\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\n"; 
echo "						    <div class=\"modal-dialog\">\n"; 
echo "						      <div class=\"modal-content\">\n"; 
echo "						        <div class=\"modal-header\">\n"; 
echo "						          <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">&times;</button>\n"; 
echo "						          <h4 class=\"modal-title\">Oceanic Sailing</h4>\n"; 
echo "						        </div>\n"; 
echo "						        <div class=\"modal-body\">\n"; 
echo "						          <p><img class=\"img-responsive\" src=\"assets/img/attractions/boat.jpg\" alt=\"\"></p>\n"; 
echo "						          <p>Be adventurous and take a trip Sailing for two on the Oceanic Sound. This nautical retreat is aboard the certified instructors and crew with a passion for the open sea. Oceanic sailing provides night and day cruising and is home to world renowned chef, Miguel Chevos. Their site includes special offers and booking options.</p>\n"; 
echo "						          <p><b><a href=\"#\">Visit Site</a></b></p>\n"; 
echo "						        </div>\n"; 
echo "						        <div class=\"modal-footer\">\n"; 
echo "						          <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\n"; 
echo "						        </div>\n"; 
echo "						      </div><!-- /.modal-content -->\n"; 
echo "						    </div><!-- /.modal-dialog -->\n"; 
echo "						  </div><!-- /.modal -->\n"; 
echo "				\n"; 
echo "				<!-- PORTFOLIO IMAGE 3 -->\n"; 
echo "				<div class=\"col-md-4\">\n"; 
echo "			    	<div class=\"grid mask\">\n"; 
echo "						<figure>\n"; 
echo "							<img class=\"img-responsive\" src=\"assets/img/attractions/hibachi.jpg\" alt=\"\">\n"; 
echo "							<figcaption>\n"; 
echo "								<h5>Hibachi House</h5>\n"; 
echo "								<a data-toggle=\"modal\" href=\"#myModal3\" class=\"btn btn-primary btn-lg\">Take a Look</a>\n"; 
echo "							</figcaption><!-- /figcaption -->\n"; 
echo "						</figure><!-- /figure -->\n"; 
echo "			    	</div><!-- /grid-mask -->\n"; 
echo "				</div><!-- /col -->\n"; 
echo "			</div><!-- /row -->\n"; 
echo "\n"; 
echo "					<div class=\"modal fade\" id=\"myModal3\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\n"; 
echo "						    <div class=\"modal-dialog\">\n"; 
echo "						      <div class=\"modal-content\">\n"; 
echo "						        <div class=\"modal-header\">\n"; 
echo "						          <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">&times;</button>\n"; 
echo "						          <h4 class=\"modal-title\">Sebajun’s Hibachi House</h4>\n"; 
echo "						        </div>\n"; 
echo "						        <div class=\"modal-body\">\n"; 
echo "						          <p><img class=\"img-responsive\" src=\"assets/img/attractions/hibachi.jpg\" alt=\"\"></p>\n"; 
echo "						          <p>Enjoy exciting and authentic Japanese cuisine at Sebajun’s Hibachi House. The Hibachi artistry has been professionally studied by Sebajun’s team of chefs and sui chefs. Hibachi is a form of cooking where the food is cooked right in front of you. These chefs don’t only cook but perform. Check out their site for demonstration videos and menus. </p>\n"; 
echo "						          <p><b><a href=\"#\">Visit Site</a></b></p>\n"; 
echo "						        </div>\n"; 
echo "						        <div class=\"modal-footer\">\n"; 
echo "						          <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\n"; 
echo "						        </div>\n"; 
echo "						      </div><!-- /.modal-content -->\n"; 
echo "						    </div><!-- /.modal-dialog -->\n"; 
echo "						  </div><!-- /.modal -->\n"; 
echo "\n"; 
echo "\n"; 
echo "				<!-- PORTFOLIO IMAGE 4 -->\n"; 
echo "			<div class=\"row\">	\n"; 
echo "				<div class=\"col-md-4 \">\n"; 
echo "			    	<div class=\"grid mask\">\n"; 
echo "						<figure>\n"; 
echo "							<img class=\"img-responsive\" src=\"assets/img/attractions/dine.jpg\" alt=\"\">\n"; 
echo "							<figcaption>\n"; 
echo "								<h5>Italian Dining</h5>\n"; 
echo "								<a data-toggle=\"modal\" href=\"#myModal4\" class=\"btn btn-primary btn-lg\">Take a Look</a>\n"; 
echo "							</figcaption><!-- /figcaption -->\n"; 
echo "						</figure><!-- /figure -->\n"; 
echo "			    	</div><!-- /grid-mask -->\n"; 
echo "				</div><!-- /col -->\n"; 
echo "\n"; 
echo "						<div class=\"modal fade\" id=\"myModal4\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\n"; 
echo "						    <div class=\"modal-dialog\">\n"; 
echo "						      <div class=\"modal-content\">\n"; 
echo "						        <div class=\"modal-header\">\n"; 
echo "						          <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">&times;</button>\n"; 
echo "						          <h4 class=\"modal-title\">Amano Amour</h4>\n"; 
echo "						        </div>\n"; 
echo "						        <div class=\"modal-body\">\n"; 
echo "						          <p><img class=\"img-responsive\" src=\"assets/img/attractions/dine.jpg\" alt=\"\"></p>\n"; 
echo "						          <p>Italian dining at its finest. Chef Renato Bogatta came to America to introduce a traditional and mouthwatering array of Italian cuisines. This five star restaurant is a must see attraction. Romantic candle lit dinners and crisp white table tops are a few sweet accents to the experience of Amano Amour.  </p>\n"; 
echo "						          <p><b><a href=\"#\">Visit Site</a></b></p>\n"; 
echo "						        </div>\n"; 
echo "						        <div class=\"modal-footer\">\n"; 
echo "						          <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\n"; 
echo "						        </div>\n"; 
echo "						      </div><!-- /.modal-content -->\n"; 
echo "						    </div><!-- /.modal-dialog -->\n"; 
echo "						  </div><!-- /.modal -->\n"; 
echo "				\n"; 
echo "				<!-- PORTFOLIO IMAGE 5 -->\n"; 
echo "				<div class=\"col-md-4\">\n"; 
echo "			    	<div class=\"grid mask\">\n"; 
echo "						<figure>\n"; 
echo "							<img class=\"img-responsive\" src=\"assets/img/attractions/jazz3.jpg\" alt=\"\">\n"; 
echo "							<figcaption>\n"; 
echo "								<h5>Jazz Club & Bar</h5>\n"; 
echo "								<a data-toggle=\"modal\" href=\"#myModal5\" class=\"btn btn-primary btn-lg\">Take a Look</a>\n"; 
echo "							</figcaption><!-- /figcaption -->\n"; 
echo "						</figure><!-- /figure -->\n"; 
echo "			    	</div><!-- /grid-mask -->\n"; 
echo "				</div><!-- /col -->\n"; 
echo "\n"; 
echo "						<div class=\"modal fade\" id=\"myModal5\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\n"; 
echo "						    <div class=\"modal-dialog\">\n"; 
echo "						      <div class=\"modal-content\">\n"; 
echo "						        <div class=\"modal-header\">\n"; 
echo "						          <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">&times;</button>\n"; 
echo "						          <h4 class=\"modal-title\">Uptown Jazz Club & Bar</h4>\n"; 
echo "						        </div>\n"; 
echo "						        <div class=\"modal-body\">\n"; 
echo "						          <p><img class=\"img-responsive\" src=\"assets/img/attractions/jazz3.jpg\" alt=\"\"></p>\n"; 
echo "						          <p>A small but lively scene is found at the upbeat Uptown Jazz Club & Bar. Enjoy live jazz from groups around our region. Dance the night away with a loved one or have fun with a group of friends. There is always action and thrills at this dive and the staff are superb.   </p>\n"; 
echo "						          <p><b><a href=\"#\">Visit Site</a></b></p>\n"; 
echo "						        </div>\n"; 
echo "						        <div class=\"modal-footer\">\n"; 
echo "						          <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\n"; 
echo "						        </div>\n"; 
echo "						      </div><!-- /.modal-content -->\n"; 
echo "						    </div><!-- /.modal-dialog -->\n"; 
echo "						  </div><!-- /.modal -->\n"; 
echo "				\n"; 
echo "				<!-- PORTFOLIO IMAGE 6 -->\n"; 
echo "				<div class=\"col-md-4\">\n"; 
echo "			    	<div class=\"grid mask\">\n"; 
echo "						<figure>\n"; 
echo "							<img class=\"img-responsive\" src=\"assets/img/attractions/theater.jpg\" alt=\"\">\n"; 
echo "							<figcaption>\n"; 
echo "								<h5>Performing Arts</h5>\n"; 
echo "								<a data-toggle=\"modal\" href=\"#myModal6\" class=\"btn btn-primary btn-lg\">Take a Look</a>\n"; 
echo "							</figcaption><!-- /figcaption -->\n"; 
echo "						</figure><!-- /figure -->\n"; 
echo "			    	</div><!-- /grid-mask -->\n"; 
echo "				</div><!-- /col -->\n"; 
echo "\n"; 
echo "						<div class=\"modal fade\" id=\"myModal6\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\n"; 
echo "						    <div class=\"modal-dialog\">\n"; 
echo "						      <div class=\"modal-content\">\n"; 
echo "						        <div class=\"modal-header\">\n"; 
echo "						          <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">&times;</button>\n"; 
echo "						          <h4 class=\"modal-title\">International Performing Arts Center of Elmwood</h4>\n"; 
echo "						        </div>\n"; 
echo "						        <div class=\"modal-body\">\n"; 
echo "						          <p><img class=\"img-responsive\" src=\"assets/img/attractions/theater.jpg\" alt=\"\"></p>\n"; 
echo "						          <p>IPACE is home to a diverse and eclectic group of performers. New dance and performing companies arrive weekly to entertain a captive audience. See operas, orchestras, playwrights and classics. This theatre holds space for a thousand. Backstage views balcony, floor and upper level seats are available for matinee and evening performances.</p>\n"; 
echo "						          <p><b><a href=\"#\">Visit Site</a></b></p>\n"; 
echo "						        </div>\n"; 
echo "						        <div class=\"modal-footer\">\n"; 
echo "						          <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\n"; 
echo "						        </div>\n"; 
echo "						      </div><!-- /.modal-content -->\n"; 
echo "						    </div><!-- /.modal-dialog -->\n"; 
echo "						  </div><!-- /.modal -->\n"; 
echo "\n"; 
echo "\n"; 
echo "			</div><!-- /row -->\n"; 
echo "			<br>\n"; 
echo "			<br>\n"; 
echo "		</div><!-- /row -->\n"; 
echo "	</div><!-- /container -->\n"; 
echo "\n"; 
echo "		<div class=\"row\">\n"; 
echo "		<div class=\"container\" id=\"contact\" name=\"contact\">\n"; 
echo "			<div class=\"row\">\n"; 
echo "			<br>\n"; 
echo "				<h1 class=\"centered\">THANK YOU FOR VISITING US</h1>\n"; 
echo "				<hr>\n"; 
echo "				<br>\n"; 
echo "				<br>\n"; 
echo "				<div class=\"col-lg-4\">\n"; 
echo "					<h3>Contact Information</h3>\n"; 
echo "					<p>\n"; 
echo "						<span class=\"icon icon-phone\"></span> +34 9884 4893 <br/>\n"; 
echo "						<span class=\"icon icon-home\"></span> <a href=\"maps.google.com\" target=\"_blank\">123 Sesame Street</a><br/>\n"; 
echo "						<span class=\"icon icon-envelop\"></span> <a href=\"#\"> support@b&bwillowbrooks.co</a> <br/>\n"; 
echo "						<span class=\"icon icon-twitter\"></span> <a href=\"https://twitter.com/\" target=\"_blank\"> @blacktie_co </a> <br/>\n"; 
echo "						<span class=\"icon icon-facebook\"></span> <a href=\"https://www.facebook.com/index.php?stype=lo&lh=Ac_WyWOi3Uqs_pc9\" target=\"_blank\"> B&B WillowBrooks </a> <br/>\n"; 
echo "					</p>\n"; 
echo "				</div><!-- col -->\n"; 
echo "				\n"; 
echo "				<div class=\"col-lg-4\">\n"; 
echo "					<h3>Newsletter</h3>\n"; 
echo "					<p>Register to our newsletter and be updated with the latests information regarding our services, offers and much more.</p>\n"; 
echo "					<p>\n"; 
echo "						<form class=\"form-horizontal\" role=\"form\">\n"; 
echo "						  <div class=\"form-group\">\n"; 
echo "						    <label for=\"inputEmail1\" class=\"col-lg-4 control-label\"></label>\n"; 
echo "						    <div class=\"col-lg-10\">\n"; 
echo "						      <input type=\"email\" class=\"form-control\" id=\"inputEmail1\" placeholder=\"Email\">\n"; 
echo "						    </div>\n"; 
echo "						  </div>\n"; 
echo "						  <div class=\"form-group\">\n"; 
echo "						    <label for=\"text1\" class=\"col-lg-4 control-label\"></label>\n"; 
echo "						    <div class=\"col-lg-10\">\n"; 
echo "						      <input type=\"text\" class=\"form-control\" id=\"text1\" placeholder=\"Your Name\">\n"; 
echo "						    </div>\n"; 
echo "						  </div>\n"; 
echo "						  <div class=\"form-group\">\n"; 
echo "						    <div class=\"col-lg-10\">\n"; 
echo "						      <button type=\"submit\" class=\"btn btn-success\">Sign Up</button>\n"; 
echo "						    </div>\n"; 
echo "						  </div>\n"; 
echo "					   </form><!-- form -->\n"; 
echo "					</p>\n"; 
echo "				</div><!-- col -->\n"; 
echo "				\n"; 
echo "				<div class=\"col-lg-4\">\n"; 
echo "					<h3>Ask Us Anything</h3>\n"; 
echo "					<p>Should you have any concerns or questions regarding your stay at our location, please do not hesitate to contact us through any means of communication, listed on the left. We will be more than happy to discuss pricing availailbilty, as well as address questions and concerns. </p>\n"; 
echo "					<style>\n"; 
echo "						h3 {\n"; 
echo "							text-align: center;\n"; 
echo "						}\n"; 
echo "					</style>\n"; 
echo "				</div><!-- col -->\n"; 
echo "\n"; 
echo "			</div><!-- row -->\n"; 
echo "		\n"; 
echo "		</div><!-- container -->\n"; 
echo "\n"; 
echo "		<div id=\"footerwrap\">\n"; 
echo "			<div class=\"container\">\n"; 
echo "				<h4>Theme created by <a href=\"http://blacktie.co\">BlackTie.co</a> - Copyright 2014</h4>\n"; 
echo "			</div>\n"; 
echo "		</div>\n"; 
echo "\n"; 
echo "    <!-- Bootstrap core JavaScript\n"; 
echo "    ================================================== -->\n"; 
echo "    <!-- Placed at the end of the document so the pages load faster -->\n"; 
echo "		\n"; 
echo "\n"; 
echo "	<script type=\"text/javascript\" src=\"assets/js/bootstrap.min.js\"></script>\n"; 
echo "	<script type=\"text/javascript\" src=\"assets/js/retina.js\"></script>\n"; 
echo "	<script type=\"text/javascript\" src=\"assets/js/jquery.easing.1.3.js\"></script>\n"; 
echo "    <script type=\"text/javascript\" src=\"assets/js/smoothscroll.js\"></script>\n"; 
echo "	<script type=\"text/javascript\" src=\"assets/js/jquery-func.js\"></script>\n"; 
echo "  </body>\n"; 
echo "<!-- PERMISSIONS AND COPYRIGHT INFO -->\n"; 
echo "<!-- THIS WEBSITE WAS CREATED FOR EDUCATION PURPOSES ONLY. LISTED BELOW ARE THE SOURCES THAT PROVIDED THE PICTURES USED ON THIS SITE -->\n"; 
echo "<!-- CREATORS: MEREDITH HOO, AAYUSH PAREKH, AND THOMAS SCHLIEN -->\n"; 
echo "\n"; 
echo "</html>\n"; 
echo "\n";
?>